### ISSUE TITLE
UNIX support?

### ISSUE THREAD

**Issue by JunielKatarn** [mysteryx93/FFmpeg.NET#1]
Does this library work on Linux or Mac OS X?

**Comment by mysteryx93** [comment]
I never tried. I tried to keep dependencies minimal. You can try it, and if something breaks, you can debug the code and submit a code update. If something isn't compatible with MONO, it should be minor details.

**Comment by mysteryx93** [comment]
Command piping features won't work, as "cmd" is Windows-only. But anyway, that was mostly for Avisynth, which is currently Windows-only.
