### ISSUE TITLE
Convert from jpg to mp4 or mpeg

### ISSUE THREAD

**Issue by Ledrunning** [mysteryx93/FFmpeg.NET#10]
Hello! Is it possible to convert JPEG files to mp4 video stream in your beautiful project?  
I know that ffmpeg can convert, but I didn't find this in FFmpeg.NET (f.e. command in Win cmd: ffmpeg -f image2 -i image%d.jpg video.mpg)

**Comment by mysteryx93** [comment]
It's not automatically generating that syntax although you can run FFmpegProcess with any argument. What is -f argument? In its current form, you could call MediaEncoder.Encode and specify the -f with encodeArgs, but not specifying any video codec would add -vn to it, which I believe means "preserve from source". The VN might cause trouble so you may have to specify the output codec.

**Comment by Ledrunning** [comment]
Thanks a lot!
