### ISSUE TITLE
asp.net

### ISSUE THREAD

**Issue by redquantum** [mysteryx93/FFmpeg.NET#11]
Hello dear Friend
Can I use with asp.net fileupload?

If your answer yes, please give me small example.

Thank you.

**Comment by mysteryx93** [comment]
It will work no problem; FFmpeg.NET and ASP.NET are 2 separate topics though. You'll need to do something like this:
1. Upload the file onto the server at path [P1]
2. Encode [P1] to [P2] via FFmpeg.NET (possibly from a different server if workload is high to keep the website working fluently)
3. Do what you want with [P2] file, and delete [P1]

One issue you might encounter though, is that encoding the file can take time, and reporting the progress to the user in real-time would require complex AJAX programming. Simple way will cause the page to hang (and possibly time-out) until the processing is done. There are various ways to solve this, ranging from simple to very complex, it really depends what your needs are. This client-side notification of server-side operation is a whole other topic.

I'd probably have a processing queue on the server, and a database of files and batch processes. Upload page simply uploads the file to the server and adds it to the processing queue. Client-page can auto-refresh every few seconds to display the status. The processing of the file shouldn't be done from the HTTP response thread.
