### ISSUE TITLE
Video/Audio Capturing from spesific source

### ISSUE THREAD

**Issue by irfansagir** [mysteryx93/FFmpeg.NET#2]
Hello, 
I'm just wondering that does this library promise recording video/audio from spesific source like "Web Cam", "Microphone 1" and preview them?

**Comment by mysteryx93** [comment]
I didn't think FFmpeg had such feature but FFmpeg home page says "A complete, cross-platform solution to record, convert and stream audio and video." so perhaps it does. You'd just have to figure out the command-line syntax of the features you want. Then, you can (optionally) write a class that facilitates the generation of such command line, and it could be integrated into the project. This library will help you manage the process and graphical interface while doing so, but there's currently no wrapper for those features.
