### ISSUE TITLE
Assembly reference error

### ISSUE THREAD

**Issue by cuibonobo** [mysteryx93/FFmpeg.NET#3]
I've been trying to get FFmpeg.NET to run on Visual Studio for Mac and it seems promising, but when I try create a new `ProcessStartOptions` object, for example, like this:

```csharp
ProcessStartOptions OptionsMain = new ProcessStartOptions(jobId, "", true);
```

...I get the following error in the compiler:

```txt
MainForm.cs(23,51,23,70): error CS0012: The type 'ProcessPriorityClass' is defined in an assembly that is not referenced. You must add a reference to assembly 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
```

The target framework for my project is 4.6.1, but I tried retargeting to 4.0.0 and got the same error.

**Comment by JohannesDrexler** [comment]
Have you tried adding the assembly to YOUR project that is calling this class ?

**Comment by cuibonobo** [comment]
Manually adding `<Reference Include="System" />` to my .csproj file worked. Thanks for kick-starting my brain.
