### ISSUE TITLE
ParseProgress does not parse time correctly

### ISSUE THREAD

**Issue by glauco-basilio** [mysteryx93/FFmpeg.NET#4]
Hi,

If i call ffmpeg to handle multiple outputs witth this command:

`D:\programas\ffmpeg\bin>ffmpeg -i "D:\GDrive\Running.Video\videos\entrada\4_VGR_-_ATROVERAN_-_MOBILE.mp4"  -c:a aac -strict experimental -ac 2 -b:a 64k -ar 44100 -c:
v libx264 -pix_fmt yuv420p -profile:v baseline -level 1.3 -maxrate 192K -bufsize 1M -crf 18 -r 10 -g 30 -f hls -hls_time 9 -hls_list_size 0 -s 320x180 -hls_segment_f
ilename "d:\GDrive\Running.Video\videos\saida\4_VGR_-_ATROVERAN_-_MOBILE.mp4\320x180\%03d.ts" "d:\GDrive\Running.Video\videos\saida\4_VGR_-_ATROVERAN_-_MOBILE.mp4\32
0x180\index.m3u8" -c:a aac -strict experimental -ac 2 -b:a 64k -ar 44100 -c:v libx264 -pix_fmt yuv420p -profile:v baseline -level 2.1 -maxrate 500K -bufsize 2M -crf
18 -r 10 -g 30  -f hls -hls_time 9 -hls_list_size 0 -s 480x270 -hls_segment_filename "d:\GDrive\Running.Video\videos\saida\4_VGR_-_ATROVERAN_-_MOBILE.mp4\480x270\%03
d.ts" "d:\GDrive\Running.Video\videos\saida\4_VGR_-_ATROVERAN_-_MOBILE.mp4\480x270\index.m3u8"`

The last line output is as: 

`frame= 4151 fps=130 q=-1.0 Lq=-1.0 size=N/A time=00:06:55.00 bitrate=N/A dup=0 drop=16566 speed=  13x`

and not 

`frame= 4151 fps=240 q=-1.0 Lsize=N/A time=00:06:55.00 bitrate=N/A dup=0 drop=8283 speed=  24x` as expected in parse progress.

This cause e.Status.Time to parsed as 0.

**Comment by mysteryx93** [comment]
Fixing it now, will release new version soon.
