### ISSUE TITLE
Softkill is not killing process

### ISSUE THREAD

**Issue by KarlaZinreich** [mysteryx93/FFmpeg.NET#5]
I've tried killing a long running ffmpeg process (write rtmp stream to file) with the SoftKill function from a asp.net core application. I figured that line MediaProcess.cs:44 is returning false
` if (AttachConsole((uint)process.Id)) { // returns false`

The ffmpeg process just keeps going. Of course I can kill, but this will lead to corrupt files. 

I have found a workaround that works, but not sure if it is really without caveats. 

Step 1: redirect input of process, but attaching to "Started" event of FFmpegProcess
```
               myFFmpegProcess.Options.Started += (sender, e) => {                    
                    e.Process.WorkProcess.StartInfo.RedirectStandardInput = true;
                };
```

Step 2: Stop function that sends the "q" button to the ffmpeg process

```
  public void Stop()
        {
            if (!(myFFmpegProcess.WorkProcess.HasExited))
            {
                StreamWriter inputWriter = myFFmpegProcess.WorkProcess.StandardInput;
                inputWriter.WriteLine("q");
             }
        }

```

This will tell the ffmpeg process to quit regularly and return a valid video file.
One question upfront: Why is RedirectStandardInput set to false by default? Is there any reason behind it?

**Comment by mysteryx93** [comment]
SoftKill is an issue with complex work-arounds that vary based on your environment.
```
public static class FFmpegConfig {
        /// <summary>
        /// Occurs when a process needs to be closed. This needs to be managed manually for Console applications.
        /// See http://stackoverflow.com/a/29274238/3960200
        /// </summary>
        public static CloseProcessEventHandler CloseProcess;
 }
```

FFmpegConfig exposes CloseProcess which you must override with your own implementation of SoftKill.

As for RedirectStandardInput being set to false, it is simply because we're only parsing the Error output stream. I guess it could be set to true without problem.

**Comment by RockNHawk** [comment]
does FFmpeg.NET supports .NET Core or mono?

**Comment by mysteryx93** [comment]
I haven't yet studied how to support .NET Core, but that's on the to-do list

**Comment by KarlaZinreich** [comment]
I've been using it in a .NET Core project all the time without any issues so far.

**Comment by fugaku** [comment]
@Elchzone do you have any code sample on how you do this?

**Comment by mysteryx93** [comment]
See this post for softkill, it depends on your environment http://stackoverflow.com/a/29274238/3960200
