### ISSUE TITLE
Cannot capture output

### ISSUE THREAD

**Issue by BrightSoul** [mysteryx93/FFmpeg.NET#8]
Hi there and thanks for this nice library.
I'm trying to use it on an ASP.NET Core 2.1 application on Windows 10. It's working fine but I can't seem to capture the raw output from FFmpeg. Here's my code, suppose I just want to execute `ffmpeg -version` and capture its output.

```
var startOptions = new ProcessStartOptions(FFmpegDisplayMode.None)  {  
  Priority = ProcessPriorityClass.BelowNormal
};
var ffmpeg = new FFmpegProcess(startOptions);
var status = ffmpeg.RunFFmpeg("-version");
Console.WriteLine("Completion status: " + status.ToString());
//This prints an empty output, why?
Console.WriteLine("Output: " + ffmpeg.Output);
```
The `ffmpeg.Output` property is empty but I expected it would contain the output from the `ffmpeg -version` command. What should I do to make it work?

I'm sure ffmpeg is producing some output since, if I take a look at the ASP.NET Core application console, I DO see some lines of text. It's just that is not available via the `ffmpeg.Output` property. In fact, take a look at the very last line, it's `Output: <blank>`.
```
ffmpeg version N-91454-g3ce4034308 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 7.3.1 (GCC) 20180710
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
libavutil      56. 18.102 / 56. 18.102
libavcodec     58. 21.104 / 58. 21.104
libavformat    58. 17.101 / 58. 17.101
libavdevice    58.  4.101 / 58.  4.101
libavfilter     7. 25.100 /  7. 25.100
libswscale      5.  2.100 /  5.  2.100
libswresample   3.  2.100 /  3.  2.100
libpostproc    55.  2.100 / 55.  2.100

Completion status: Success
Output: 
```

What am I doing wrong?

**Comment by BrightSoul** [comment]
I see it's working fine with other commands, such as `-i "video/test.mp4" -vn "video/test.flac"` but not for `-version`, why?

**Comment by mysteryx93** [comment]
Perhaps it's sending to a different output stream. Most operations are sending to the ErrorStream which allows for colored output. Perhaps Version is sending to the standard output stream?

**Comment by BrightSoul** [comment]
> Perhaps Version is sending to the standard output stream?

Yes, that seems to be the case. In fact, when I run this from command line, which redirecs all STDOUT to null, nothing appears on console.
```
ffmpeg -version 1> null
```
Everything shows as usual if, instead, I redirect the STDERR to null.
```
ffmpeg -version 2> null
```
Now I tried redirecting STDOUT to STDERR from C#, hoping the output would get picked:
```
var status = ffmpeg.RunFFmpeg("-version 1>&2");
```
...but the `Output` property is still empty. Any suggestions?
It seems that output redirection is somewhat ignored, in fact I cannot even redirect to file. No file gets created.
```
var status = ffmpeg.RunFFmpeg("-version > E:\\output.log");
```

**Comment by mysteryx93** [comment]
Try with this version, it is now reading both output streams
https://www.nuget.org/packages/EmergenceGuardian.FFmpeg/1.1.1

**Comment by BrightSoul** [comment]
It works, thank you so much 👍. I'm now able to capture the output even when I run `ffmpeg -version`.
I'm closing the issue. Again, thanks!

**Comment by mysteryx93** [comment]
This last patch introduced a bug where the output would not always be parsed. Just released a new version that fixed that. The Run method now takes a parameter to specify which output to parse. Also added MediaInfo.GetVersion

**Comment by BrightSoul** [comment]
Super! I've just updated to the newest release and I confirm everything is working fine.
