### ISSUE TITLE
"This instance of FFmpeg is busy" but it's not

### ISSUE THREAD

**Issue by BrightSoul** [mysteryx93/FFmpeg.NET#9]
I'd like to use the same instance of FFmpegProcess to run more than one command subsequently (not concurrently) but the error "This instance of FFmpeg is busy" occurs. For example:
```
var startOptions = new ProcessStartOptions(FFmpegDisplayMode.None) { Priority = ProcessPriorityClass.BelowNormal };
var process = new FFmpegProcess(startOptions);
var result1 = process.RunFFmpeg("-i file1.mp4");
var result2 = process.RunFFmpeg("-i file2.mp4");
```
I get the exception when I invoke RunFFmpeg for the second time. I think the problem is that the `WorkProcess` property is not set to null when the ffmpeg process has completed its first execution.

Maybe setting `WorkProcess = null;` before this line would solve the problem.
[https://github.com/mysteryx93/FFmpeg.NET/blob/d89f17b144810824d5d0a9e9934b8d6a22de1f86/FFmpeg/FFmpegProcess.cs#L214](https://github.com/mysteryx93/FFmpeg.NET/blob/d89f17b144810824d5d0a9e9934b8d6a22de1f86/FFmpeg/FFmpegProcess.cs#L214)

What do you think? Thanks in advance.

**Comment by mysteryx93** [comment]
I believe setting WorkProcess = null before return would solve the issue. Could you test it and report back? If it causes no further issue I could release a new version with that fix.

**Comment by BrightSoul** [comment]
Sorry for the delay, I'll try soon. In the meantime I've also discovered that I cannot cancel the ffmpeg process from an ASP.NET Core application (which is basically a console application). I'll try to find a cross-platform solution since ASP.NET Core can also run on Linux. I'm forking your repo and do some experimentation this weekend. I wonder if this solution might help.
[https://stackoverflow.com/questions/283128/how-do-i-send-ctrlc-to-a-process-in-c#answer-50311262](https://stackoverflow.com/questions/283128/how-do-i-send-ctrlc-to-a-process-in-c#answer-50311262)

**Comment by mysteryx93** [comment]
To cancel the process without killing the process, you have to handle the FFmpegConfig.CloseProcess event to make it work in your specific environment. The way to handle it varies depending on where it is being used.
